server:
  port: 8081
  servlet:
    context-path: /v1

spring:
  datasource:
    username: root
    password:
    url: jdbc:mysql://localhost:3306/pet+?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver


